(ns nickdex.grain.pedestal.assets
  "The browser-side scripts, as routes.

   Routes rather than files, because both scripts are GENERATED by their
   libraries from the paths they expect to be mounted at -- a copy on
   disk is a copy that can disagree with them.

   They must reach the browser through <head>. A Datastar page's body
   arrives as an SSE patch applied by DOM morphing, and a <script>
   element inserted that way never runs -- which is exactly how the
   ceremony first shipped: a silent no-op behind a button, with a
   ReferenceError in a console nobody was reading. Inline event
   ATTRIBUTES do survive morphing, which is how the buttons reach these.

   Each URL carries a stamp of its own content. A service worker caches
   shell assets by URL and will serve a stale one forever otherwise, and
   a generated asset has no file to stat -- so the content is the stamp."
  (:require [clojure.java.io :as io]
            [nickdex.grain.auth.interface :as auth]
            [nickdex.grain.push.interface :as push]
            [ring.util.response :as ring-response]))

(defn- stamp [content] (Integer/toHexString (hash content)))

(defn- js-response [body]
  {:status 200
   :headers {"Content-Type" "text/javascript"
             ;; Immutable: the URL carries a stamp of the content, so a
             ;; changed script is a changed URL.
             "Cache-Control" "public, max-age=31536000, immutable"}
   :body body})

(def ^:private scripts
  "The two <head> scripts and their stamps.

   Memoised, and not as an optimisation to be tidied away later:
   head-scripts is called by the Datastar shim on EVERY page render, so
   without this each request rebuilt several KB of JavaScript and hashed
   it, to arrive at the same answer it had last time. Keyed on the one
   input that changes them rather than on the whole config, which carries
   a datasource and has no business being a cache key."
  (memoize
   (fn [after]
     (let [passkey (auth/ceremony-script {})
           push (push/client-script {:after after})]
       {:passkey passkey
        :push push
        :passkey-stamp (stamp passkey)
        :push-stamp (stamp push)}))))

(defn asset-path
  "A classpath resource path, stamped so a changed file arrives under a
   changed URL.

   For an application's OWN static files -- a stylesheet, a bundle -- so
   they invalidate the same way the generated scripts here do. A service
   worker caches shell assets by URL and serves them without
   revalidating, which means an unstamped stylesheet is served forever.

   The stamp is the file's last-modified time: it changes exactly when
   the file does, and costs a stat rather than reading the whole file on
   every render. An absent resource returns the bare path instead of
   throwing, because a missing asset should fail as a 404 you can see and
   not as a 500 during render."
  [path]
  (if-some [modified (some-> (io/resource (str "public" path))
                             ring-response/resource-data
                             :last-modified
                             .getTime)]
    (str path "?v=" (Long/toHexString modified))
    path))

(defn head-scripts
  "Hiccup <script> tags for the Datastar shim's <head>.

   Put them in `:datastar/shim-opts {:head ...}` alongside whatever else
   the application loads there."
  [{:keys [paths]}]
  (let [{:keys [passkey-stamp push-stamp]} (scripts (:account paths))]
    (list
     [:script {:type "module" :src (str "/passkey.js?v=" passkey-stamp)}]
     [:script {:type "module" :src (str "/push.js?v=" push-stamp)}])))

(defn routes
  "Serves /passkey.js, /push.js and a composed /sw.js.

   `:service-worker-shell` is a classpath resource holding the
   application's OWN worker -- caching, offline, update handling. The
   push and notificationclick handlers are appended from grain-push, so
   the library owns what a push must do (notably that userVisibleOnly
   makes showing a notification mandatory) and the application owns
   caching.

   A worker is registered by URL and cannot be assembled in the browser,
   which is why this is a route. Keep the shell OUTSIDE public/, or it
   is also served statically at another path and the two drift.

   Omit `:service-worker-shell` and no /sw.js route is produced -- for an
   application that has no service worker, or serves its own."
  [{:keys [service-worker-shell notification-icon paths]}]
  (let [{:keys [passkey push]} (scripts (:account paths))]
    (cond-> #{["/passkey.js" :get [(fn [_] (js-response passkey))]
               :route-name ::passkey-script]
              ["/push.js" :get [(fn [_] (js-response push))]
               :route-name ::push-script]}
      service-worker-shell
      (conj ["/sw.js" :get
             [(fn [_]
                (-> (js-response
                     (str (slurp (io/resource service-worker-shell))
                          (push/service-worker-script {:icon notification-icon})))
                    ;; NOT immutable. A worker is how an app updates
                    ;; itself; pinning it for a year means shipping a bug
                    ;; nobody can replace.
                    (assoc-in [:headers "Cache-Control"] "no-cache")))]
             :route-name ::service-worker]))))
